export const defaultTheme = {
  colors: {
    black: "#121212",
    blackTwo: "#191919",
    blackGreyOne: "#555555",
    white: "#FFFFFF",
    whiteTwo: "#D3D3D3",
    whiteThree: "#313131",
    blue: '#4785FE',
    blueOne: '#6B9DFE',
    greyOne: "#F9F9F9",
    greyTwo: "#A0A0A0",
    greyThree: "#E3E1D3",
    greyFour: "#EEEEEF",
    greyFive: "#444444",
    greySix: "#979797",
    greySeven: "#D5D5D5",
    greyEight: "#8B8B8B",
  },
  fontFamily: {
    dual_sm: "Dual-300",
    dual_lg: "Dual-600",
    hnt: "Helvetica Now Text",
    hnt_light: "Helvetica Now Text Light",
    hnt_medium: "Helvetica Now Text Medium",
    hnt_bold: "Helvetica Now Text Bold",
    hnt_extra_bold: "Helvetica Now Text Extra Bold",
    hnt_black: "Helvetica Now Text Black"
  },
  fontSize: {
    xsm: "12px",
    sm: "14px",
    m: "16px",
    lg: "28px",
    xlg: "32px",
    max: "42px",
  },
  lineHeight: {
    default: "16.14",
  },
  radii: {
    xs: "4px",
    sm: "8px",
    md: "12px",
    lg: "20px",
    circle: "50%",
    pill: "500px"
  },
  breakpoints: {
    xs: '300px',
    sm: '600px',
    md: '960px',
    lg: '1280px',
    xl: '1920px',
  },
};